/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package virtual.pet.shelter;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        
        VirtualPetShelter pet = new VirtualPetShelter();
        Scanner userInput = new Scanner(System.in);
        int select;
        
        
        System.out.println("Hello, and welcome to The Land's Between Pet Shelter. Thank you for volunteering to care for the dogs today.");
        System.out.println("While you are here, you will be responsible for admitting and adopting dogs as well as feeding, providing water, and playing games with the dogs.");
        System.out.println("We are very short staffed today. We really appreciate all the help we can get.");

        do{
            menu();

            select = Integer.parseInt(userInput.nextLine());
            pet.displayDogs();
            
            switch (select) {
                case 1:
                    System.out.println("Type in the name of the pet you would like to admit:");
                    String name = userInput.nextLine();
                    pet.admitPet(name);
                    break;
                case 2:
                    pet.feedPets();
                    break;
                case 3:
                    pet.waterPets();
                    break;
                case 4:
                    pet.playWithPets();
                    break;
                case 5:
                    System.out.println("Type in the name of the pet you would like to adopt:");
                    String adoptingPet = userInput.nextLine();
                    pet.adoptPet(adoptingPet);
                    break;
                case 6:
                System.out.println("Thank you for your help today.  We hope to see you again!");
                System.exit(0);    
                default:
                    break;
            }
        }while(select != 6);
        
        userInput.close();
    }
    
    public static void menu(){
            System.out.println("What action will you take to care for the dogs?");
            System.out.println("1. Admit dog.");
            System.out.println("2. Feed them some food.");
            System.out.println("3. Give them some water.");
            System.out.println("4. Play games with the dogs ");
            System.out.println("5. Release dog to adopted owners");
            System.out.println("6. Exit" );
            System.out.println("");
    }

    }





