/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package virtual.pet.shelter;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        
        VirtualPetShelter pet = new VirtualPetShelter();
        Scanner userInput = new Scanner(System.in);
        int select;
        String name = userInput.nextLine();
        
        System.out.println("Hello, and welcome to The Land's Between Pet Shelter. Thank you for volunteering to care for the dogs today.");
        System.out.println("While you are here, you will be responsible for admitting and adopting dogs as well as feeding, providing water, and playing games with the dogs.");
        System.out.println("We are very short staffed today. We really appreciate all the help we can get.");

        do{
            select = Integer.parseInt(userInput.nextLine());
            pet.displayDogs();

            menu();

            switch (select) {
                case 1:
                    admitPet();
                    break;
                case 2:
                    pet.feedPets();
                    break;
                case 3:
                    pet.waterPets();
                    break;
                case 4:
                    pet.playWithPets();

                case 5:
                    pet.adoptPet(name); 
                case 6:
                System.out.println("Thank you for your help today.  We hope to see you again!");
                System.exit(0);    
                default:
                    break;
            }
        }while(select != 6);
        scanner.close();
    }
    
    public static void menu(){
            System.out.println("What action will you take to care for the dogs?");
            System.out.println("1. Admit dog.");
            System.out.println("2. Feed them some food.");
            System.out.println("3. Give them some water.");
            System.out.println("4. Play games with the dogs ");
            System.out.println("5. Release dog to adopted owners");
            System.out.println("6. Exit" );
    }

    public static void adoptPet(String name, Scanner scanner){
        System.out.println("Which dog are you interested in adopting?");
        scanner.next();
    }



}

